### ISSUE TITLE
Feature: Database

### ISSUE THREAD

**Issue by Stranger6667** [Rik-de-Kort/minithesis-rust#4]
If you don't mind, I'd like to work on the `DirectoryDB` implementation

**Comment by Rik-de-Kort** [comment]
I was dreading that! Please go for it!

**Comment by Rik-de-Kort** [comment]
@Stranger6667 how's work coming along?

**Comment by Stranger6667** [comment]
I took a look at the Hypothesis version and implemented it feature-wise, including iterators, original tests, etc. However, there are maybe some little cleanup issues and it is ready. I created a separate crate for better isolation / testing, will push in a few days as a subcrate

**Comment by Rik-de-Kort** [comment]
Closed by #9
